CREATE TABLE companies (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    industry VARCHAR(100),
    address VARCHAR(255),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE users
ADD COLUMN role VARCHAR(20) DEFAULT 'staff',
ADD COLUMN status VARCHAR(10) DEFAULT 'active',
ADD COLUMN company_id INT,
ADD CONSTRAINT fk_company FOREIGN KEY (company_id) REFERENCES companies(id);
